<?php

namespace Database\Seeders;

use App\Models\SpektrumFrekuensi;
use Illuminate\Database\Seeder;

class SpektrumFrekuensiSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'id' => 1,
                'CLNT_ID' => 12001,
                'NO_SIMF' => '0760217',
                'APPL_ID' => '15025092019',
                'SITE_ID' => 1,
                'CLNT_NAME' => 'PT Radio Lokal Minahasa',
                'STATUS_SIMF' => 'DENDA',
                'PHONE' => '0431-111222',
                'SERVICE' => 'Broadcast',
                'SUBSERVICE' => 'FM',
                'TRANS_TYPE' => 'Transmitter',
                'FREQ' => 99.5,
                'STN_NAME' => 'Radio FM Minahasa',
                'STN_ADDR' => 'JL. TRANS SULAWESI',
                'CALLSIGN' => 'YKZZ',
                'SID_LONG' => 124.920000,
                'SID_LAT' => 1.380000,
                'VALIDITY_DATE' => '2024-12-31',
                'CITY' => 'MINAHASA',
                'DISTRICT' => 'TONDANO SELATAN',
                'PROVINCE' => 'SULAWESI UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'CLNT_ID' => 1035,
                'NO_SIMF' => '02147074-000SU/2020192024',
                'APPL_ID' => '15025092019',
                'SITE_ID' => 1,
                'CLNT_NAME' => 'LPP RRI Manado',
                'STATUS_SIMF' => 'GRANTED',
                'PHONE' => '0431-862555',
                'SERVICE' => 'Broadcast',
                'SUBSERVICE' => 'AM',
                'TRANS_TYPE' => 'Transmitter',
                'FREQ' => 95.5,
                'STN_NAME' => 'RRI Manado Pro 1',
                'STN_ADDR' => 'JL. DIPONEGORO NO. 1',
                'CALLSIGN' => 'YKAA',
                'SID_LONG' => 124.842100,
                'SID_LAT' => 1.474800,
                'VALIDITY_DATE' => '2029-09-17',
                'CITY' => 'KOTA MANADO',
                'DISTRICT' => 'WENANG',
                'PROVINCE' => 'SULAWESI UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'CLNT_ID' => 109695,
                'NO_SIMF' => '01870219-000SU/2620162021',
                'APPL_ID' => '37832042016',
                'SITE_ID' => 8,
                'CLNT_NAME' => 'CV Palopo Star',
                'STATUS_SIMF' => 'Granted',
                'PHONE' => '-',
                'SERVICE' => 'Land Mobile (private)',
                'SUBSERVICE' => 'Standard',
                'TRANS_TYPE' => 'Transmitter',
                'FREQ' => 155.1,
                'STN_NAME' => 'BS. CV. Palopo Star 5',
                'STN_ADDR' => 'BORGO II JAGA II',
                'CALLSIGN' => 'J3EJN',
                'SID_LONG' => 124.783836,
                'SID_LAT' => 0.923258,
                'VALIDITY_DATE' => '2026-05-09',
                'CITY' => 'MINAHASA TENGGARA',
                'DISTRICT' => 'BELANG',
                'PROVINCE' => 'SULAWESI UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'CLNT_ID' => 112437,
                'NO_SIMF' => '1279/DU/SDPPI/2024',
                'APPL_ID' => '134062024',
                'CLNT_NAME' => 'AirNav Indonesia',
                'STATUS_SIMF' => 'Granted',
                'PHONE' => '0431-814376',
                'SERVICE' => 'Aeronautical',
                'SUBSERVICE' => 'Ground-To-Air',
                'TRANS_TYPE' => 'Transmitter',
                'FREQ' => 123.0,
                'STN_NAME' => 'NDB PN',
                'STN_ADDR' => 'PANIKI ATAS',
                'CALLSIGN' => 'WAAA',
                'SID_LONG' => 124.909444,
                'SID_LAT' => 1.493333,
                'VALIDITY_DATE' => '2029-07-09',
                'CITY' => 'MINAHASA UTARA',
                'DISTRICT' => 'TALAWAAN',
                'PROVINCE' => 'SULAWESI UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'CLNT_ID' => 13001,
                'NO_SIMF' => 'MAR-001-SU',
                'APPL_ID' => 'MAR202501',
                'SITE_ID' => 2,
                'CLNT_NAME' => 'Pelindo Bitung',
                'STATUS_SIMF' => 'GRANTED',
                'PHONE' => '0438-31234',
                'SERVICE' => 'Maritim',
                'SUBSERVICE' => 'Harbor',
                'TRANS_TYPE' => 'Transmitter',
                'FREQ' => 156.8,
                'STN_NAME' => 'Radio Coast Station Bitung',
                'STN_ADDR' => 'PELABUHAN BITUNG',
                'CALLSIGN' => 'YC-BTG',
                'SID_LONG' => 125.199000,
                'SID_LAT' => 1.441000,
                'VALIDITY_DATE' => '2028-04-30',
                'CITY' => 'BITUNG',
                'DISTRICT' => 'MAESA',
                'PROVINCE' => 'SULAWESI UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($records as $record) {
            SpektrumFrekuensi::query()->updateOrCreate(
                ['id' => $record['id']],
                $record,
            );
        }
    }
}
